ALTER TYPE "AthletePosition" ADD VALUE IF NOT EXISTS 'RIGHT_BACK';
ALTER TYPE "AthletePosition" ADD VALUE IF NOT EXISTS 'LEFT_BACK';
ALTER TYPE "AthletePosition" ADD VALUE IF NOT EXISTS 'DEFENSIVE_MIDFIELDER';
ALTER TYPE "AthletePosition" ADD VALUE IF NOT EXISTS 'CENTRAL_MIDFIELDER';
ALTER TYPE "AthletePosition" ADD VALUE IF NOT EXISTS 'ATTACKING_MIDFIELDER';
ALTER TYPE "AthletePosition" ADD VALUE IF NOT EXISTS 'RIGHT_WINGER';
ALTER TYPE "AthletePosition" ADD VALUE IF NOT EXISTS 'LEFT_WINGER';
ALTER TYPE "AthletePosition" ADD VALUE IF NOT EXISTS 'STRIKER';
