CREATE TABLE "PlatformSettings" (
  "id" TEXT NOT NULL DEFAULT 'default',
  "platformName" TEXT NOT NULL DEFAULT 'GestaSports',
  "supportEmail" TEXT NOT NULL DEFAULT 'suporte@gestasports.com.br',
  "commercialEmail" TEXT NOT NULL DEFAULT 'comercial@gestasports.com.br',
  "baseDomain" TEXT NOT NULL DEFAULT 'gestasports.com.br',
  "defaultTrialDays" INTEGER NOT NULL DEFAULT 14,
  "defaultImplementationDays" INTEGER NOT NULL DEFAULT 7,
  "defaultBillingGraceDays" INTEGER NOT NULL DEFAULT 7,
  "defaultMonthlyDueDay" INTEGER NOT NULL DEFAULT 10,
  "autoSuspendEnabled" BOOLEAN NOT NULL DEFAULT true,
  "autoReactivateEnabled" BOOLEAN NOT NULL DEFAULT true,
  "requireVerifiedDomain" BOOLEAN NOT NULL DEFAULT false,
  "allowPathAccess" BOOLEAN NOT NULL DEFAULT true,
  "defaultProvisioningMode" TEXT NOT NULL DEFAULT 'AUTOMATIC',
  "tenantNamingPattern" TEXT NOT NULL DEFAULT '{slug}',
  "auditRetentionDays" INTEGER NOT NULL DEFAULT 180,
  "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
  "updatedAt" TIMESTAMP(3) NOT NULL,

  CONSTRAINT "PlatformSettings_pkey" PRIMARY KEY ("id")
);

INSERT INTO "PlatformSettings" (
  "id",
  "platformName",
  "supportEmail",
  "commercialEmail",
  "baseDomain",
  "defaultTrialDays",
  "defaultImplementationDays",
  "defaultBillingGraceDays",
  "defaultMonthlyDueDay",
  "autoSuspendEnabled",
  "autoReactivateEnabled",
  "requireVerifiedDomain",
  "allowPathAccess",
  "defaultProvisioningMode",
  "tenantNamingPattern",
  "auditRetentionDays",
  "updatedAt"
) VALUES (
  'default',
  'GestaSports',
  'suporte@gestasports.com.br',
  'comercial@gestasports.com.br',
  'gestasports.com.br',
  14,
  7,
  7,
  10,
  true,
  true,
  false,
  true,
  'AUTOMATIC',
  '{slug}',
  180,
  CURRENT_TIMESTAMP
);
