CREATE TYPE "GameStatus" AS ENUM ('SCHEDULED', 'RUNNING', 'PAUSED', 'FINISHED');

ALTER TABLE "Game"
ADD COLUMN "status" "GameStatus" NOT NULL DEFAULT 'SCHEDULED',
ADD COLUMN "halfDurationMinutes" INTEGER NOT NULL DEFAULT 45,
ADD COLUMN "breakDurationMinutes" INTEGER NOT NULL DEFAULT 15,
ADD COLUMN "startedAt" TIMESTAMP(3),
ADD COLUMN "pausedAt" TIMESTAMP(3),
ADD COLUMN "elapsedSeconds" INTEGER NOT NULL DEFAULT 0,
ADD COLUMN "finishedAt" TIMESTAMP(3);
