ALTER TYPE "AthletePosition" ADD VALUE IF NOT EXISTS 'DEFENDER';
ALTER TYPE "AthletePosition" ADD VALUE IF NOT EXISTS 'FULLBACK';
ALTER TYPE "AthletePosition" ADD VALUE IF NOT EXISTS 'MIDFIELDER';
ALTER TYPE "AthletePosition" ADD VALUE IF NOT EXISTS 'FORWARD';
